# Generated by Django 3.2 on 2021-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('thumbnail', models.URLField(max_length=500)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
