# Generated by Django 3.2 on 2021-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
